import { StyleSheet } from '@react-pdf/renderer';
import { styles as importedStyles } from '../../reportStyles';

// Base styles that are common across different sections
export const baseStyles = StyleSheet.create({
  ...importedStyles,
  page: {
    padding: 30,
    fontSize: 10,
    fontFamily: 'Helvetica',
    position: 'relative',
  },
  reportHeader: {
    marginBottom: 14,
    borderBottom: '1.5px solid #444444',
    paddingBottom: 8,
  },
  reportTitle: {
    fontSize: 18,
    marginBottom: 4,
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Helvetica-Bold',
  },
  reportSubtitle: {
    fontSize: 10,
    textAlign: 'center',
    color: '#444444',
    marginBottom: 4,
  },
  singleColumnContent: {
    flexDirection: 'column',
    flexGrow: 1,
  },
  text: {
    fontSize: 10,
    marginBottom: 5,
    lineHeight: 1.4,
    fontFamily: 'Helvetica',
  },
  sectionHeader: {
    backgroundColor: '#000000',
    color: '#FFFFFF',
    padding: 6,
    marginBottom: 6,
    fontSize: 11,
    fontWeight: 'bold',
    fontFamily: 'Helvetica-Bold',
  },
  grayBackground: {
    backgroundColor: '#F5F5F5',
    padding: 8,
  },
  pageNumber: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 8,
    fontFamily: 'Helvetica',
  },
  footer: {
    position: 'absolute',
    bottom: 10,
    left: 30,
    fontSize: 6,
    color: '#666666',
    fontFamily: 'Helvetica',
  },
  disclaimerText: {
    fontSize: 8,
    marginTop: 3,
    lineHeight: 1.3,
    color: '#444444',
    fontFamily: 'Helvetica',
  },
  page: {
    padding: 30,
    fontSize: 10,
    fontFamily: 'Helvetica',
    position: 'relative',
    backgroundColor: '#FFFFFF',
  },
  sectionHeader: {
    backgroundColor: '#000000',
    color: '#FFFFFF',
    padding: 8,
    marginBottom: 10,
    fontSize: 11,
    fontWeight: 'bold',
    fontFamily: 'Helvetica-Bold',
  },
  subsectionHeader: {
    backgroundColor: '#F5F5F5',
    padding: 6,
    marginBottom: 8,
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
  },
  fieldContainer: {
    marginBottom: 8,
    borderBottom: '1px solid #CCCCCC',
  },
  fieldRow: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  fieldLabel: {
    width: '30%',
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
  },
  fieldValue: {
    width: '70%',
    fontSize: 10,
  },
  section: {
    marginBottom: 15,
    fontFamily: 'Helvetica',
  },
  compactGroup: {
    flexDirection: 'row',
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  indentedGroup: {
    marginLeft: 12,
    marginTop: 4,
  },
  boldLabel: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 10,
    marginRight: 4,
  },
  normalText: {
    fontFamily: 'Helvetica',
    fontSize: 10,
  },
  mainTitle: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 12,
    marginBottom: 8,
    color: '#333333',
  },
  sectionGap: {
    marginTop: 8,
  },
  table: {
    display: 'flex',
    width: 'auto',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  tableTitle: {
    margin: 8,
    fontSize: 12,
    fontWeight: 'bold',
  },
  tableRow: { 
    flexDirection: 'row',
    borderBottomColor: '#000',
    borderBottomWidth: 1,
    alignItems: 'stretch',
    minHeight: 30,
    fontFamily: 'Helvetica',
    fontSize: 9,
  },
  tableHeader: {
    backgroundColor: '#f0f0f0',
    flexDirection: 'row',
    borderBottomColor: '#000',
    borderBottomWidth: 1,
    alignItems: 'center',
    height: 24,
    fontFamily: 'Helvetica-Bold',
    fontSize: 9,
  },
  indexCell: {
    width: '4%',
    borderRightColor: '#000',
    borderRightWidth: 1,
    paddingLeft: 2,
    paddingRight: 2,
    paddingTop: 4,
    paddingBottom: 4,
  },
  cell: {
    width: '12%',
    borderRightColor: '#000',
    borderRightWidth: 1,
    paddingLeft: 2,
    paddingRight: 2,
    paddingTop: 4,
    paddingBottom: 4,
    display: 'flex',
    flexWrap: 'wrap',
  },
  classificationCell: {
    width: '24%',
    borderRightColor: '#000',
    borderRightWidth: 1,
    paddingLeft: 2,
    paddingRight: 2,
    paddingTop: 4,
    paddingBottom: 4,
  },
  subTitle: {
    fontSize: 12,
    marginBottom: 8,
    fontWeight: 'bold',
    fontFamily: 'Helvetica-Bold',
  },
  // New styles for the formal medical report
  blackHeader: {
    backgroundColor: '#000000',
    color: '#FFFFFF',
    padding: 6,
    marginBottom: 8,
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
  },
  dataRow: {
    flexDirection: 'row',
    marginBottom: 10,
    borderBottom: '1px solid #CCCCCC',
  },
  labelCell: {
    width: '30%',
    padding: 4,
    fontSize: 10,
    fontFamily: 'Helvetica',
  },
  valueCell: {
    width: '70%',
    padding: 4,
    fontSize: 10,
    fontFamily: 'Helvetica',
    borderLeft: '1px solid #CCCCCC',
  },
  grayBackground: {
    backgroundColor: '#F2F2F2',
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'Helvetica-Bold',
    marginBottom: 5,
    marginTop: 10,
  }
});
