
import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#fff',
    padding: 30,
  },
  section: {
    marginBottom: 10,
  },
  title: {
    fontSize: 20,
    textAlign: 'left',
    marginBottom: 20,
    fontFamily: 'Helvetica-Bold',
  },
  header: {
    fontSize: 16,
    marginBottom: 8,
    fontFamily: 'Helvetica-Bold',
  },
  subheader: {
    fontSize: 12,
    marginBottom: 6,
    marginTop: 8,
    fontFamily: 'Helvetica-Bold',
    borderBottom: '1 solid #CCCCCC',
    paddingBottom: 2,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  label: {
    width: 150,
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    textAlign: 'left',
  },
  value: {
    fontSize: 10,
    fontFamily: 'Helvetica',
  },
  footer: {
    position: 'absolute',
    fontSize: 10,
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: 'center',
    color: 'grey',
  },
  pageNumber: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 8,
  },
  reportFooter: {
    fontSize: 9,
    marginTop: 15,
    textAlign: 'center',
    fontFamily: 'Helvetica',
  },
  summaryBox: {
    marginBottom: 8,
    padding: 6,
    backgroundColor: '#f8f8f8',
    borderRadius: 4,
  },
  summaryText: {
    fontSize: 9,
    lineHeight: 1.3,
    color: '#333333',
    fontFamily: 'Helvetica',
  },
  sectionTitle: {
    backgroundColor: '#000000',
    color: '#FFFFFF',
    padding: 6,
    marginBottom: 8,
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
  },
  subsection: {
    marginBottom: 10,
    paddingLeft: 5,
  },
  infoTable: {
    display: 'flex',
    flexDirection: 'column',
    marginBottom: 10,
    width: '100%',
    borderWidth: 1,
    borderColor: '#DDDDDD',
  },
  infoRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#DDDDDD',
    width: '100%',
  },
  cellContainer: {
    width: '50%',
    borderRightWidth: 1,
    borderRightColor: '#DDDDDD',
  },
  infoHeader: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    padding: 4,
    paddingBottom: 2,
    borderBottomWidth: 1,
    borderBottomColor: '#DDDDDD',
    textAlign: 'left',
  },
  infoCell: {
    padding: 4,
    paddingTop: 3,
    fontSize: 9,
    fontFamily: 'Helvetica',
    lineHeight: 1.2,
  },
  rightCell: {
    padding: 4,
    paddingTop: 3,
    fontSize: 9,
    fontFamily: 'Helvetica',
    lineHeight: 1.2,
  },
  reportIdentifier: {
    fontSize: 8,
    color: '#666666',
    marginTop: 15,
    marginBottom: 5,
  },
  pageIndicator: {
    fontSize: 8,
    textAlign: 'right',
  },
  compactSubsection: {
    marginBottom: 8,
    paddingLeft: 3,
  },
  compactRow: {
    flexDirection: 'row',
    marginBottom: 3,
  },
  compactLabel: {
    width: 120,
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    textAlign: 'left',
  },
  compactValue: {
    fontSize: 9,
    fontFamily: 'Helvetica',
  },
  compactSectionTitle: {
    backgroundColor: '#000000',
    color: '#FFFFFF',
    padding: 4,
    marginBottom: 6,
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
  },
});
