// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojqfiilgkhigkoezksnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qcWZpaWxna2hpZ2tvZXprc25yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NjIxOTQsImV4cCI6MjA1NDQzODE5NH0.pNcgT57i6yYDkBkZRyD0h7NpexePvCHp8RNVQv3YviA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);